INCFLAGS  = -I ./include
INCFLAGS += -I ./include/vecmath

LINKFLAGS  = -lglut -lGL -lGLU
LINKFLAGS += -L ./lib -lvecmath

CFLAGS    = -O2
CC        = g++
SRCS      = main.cpp
OBJS      = $(SRCS:.cpp=.o)
PROG      = a0

all: $(SRCS) $(PROG)

$(PROG): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@ $(INCFLAGS) $(LINKFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -c -o $@ $(INCFLAGS)

depend:
	makedepend $(INCFLAGS) -Y $(SRCS)

clean:
	rm $(OBJS) $(PROG)

# DO NOT DELETE

main.o: ./include/GL/freeglut.h ./include/GL/freeglut_std.h
main.o: ./include/GL/freeglut_ext.h ./include/vecmath/vecmath.h
main.o: ./include/vecmath/Matrix2f.h ./include/vecmath/Matrix3f.h
main.o: ./include/vecmath/Matrix4f.h ./include/vecmath/Quat4f.h
main.o: ./include/vecmath/Vector2f.h ./include/vecmath/Vector3f.h
main.o: ./include/vecmath/Vector4f.h
